# Generated by Django 4.1.4 on 2023-01-07 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inbox_messages", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inboxes",
            name="recipient",
        ),
    ]
