# Generated by Django 4.1.4 on 2023-01-08 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inbox_messages", "0003_inboxes_recipient_alter_inboxes_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inboxes",
            name="is_new",
        ),
    ]
