# Generated by Django 4.1.4 on 2023-01-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox_messages", "0004_remove_inboxes_is_new"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inboxes",
            old_name="is_read",
            new_name="is_read_by_recipient",
        ),
        migrations.AddField(
            model_name="inboxes",
            name="is_read_by_sender",
            field=models.BooleanField(default=False),
        ),
    ]
