# Generated by Django 4.1.4 on 2023-01-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox_messages", "0005_rename_is_read_inboxes_is_read_by_recipient_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserIdMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("random_string", models.CharField(max_length=32)),
            ],
        ),
    ]
