# Generated by Django 4.1.4 on 2023-01-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox_messages", "0006_useridmapping"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserIdMapping",
        ),
        migrations.AddField(
            model_name="chat",
            name="recipient_token",
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name="chat",
            name="sender_token",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
