# Generated by Django 4.1.4 on 2023-02-10 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inbox_messages", "0007_delete_useridmapping_chat_recipient_token_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="subject",
        ),
    ]
