# Generated by Django 4.1.4 on 2023-02-11 02:41

from django.db import migrations, models
import inbox_messages.models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox_messages", "0008_remove_chat_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboxes",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=inbox_messages.models.user_directory_path,
            ),
        ),
    ]
