# Generated by Django 4.1.4 on 2023-02-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox_messages", "0010_rename_file_inboxes_vid_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inboxes",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
