# Generated by Django 4.1.4 on 2023-02-19 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox_messages", "0011_alter_inboxes_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboxes",
            name="vid_img_size",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
