# Generated by Django 4.1.4 on 2023-02-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox_messages", "0012_inboxes_vid_img_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboxes",
            name="vid_img_poster",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
