# Generated by Django 4.1.4 on 2023-02-19 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inbox_messages", "0015_alter_inboxes_vid_img_poster"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inboxes",
            name="vid_img_poster",
        ),
    ]
