# Generated by Django 4.1.4 on 2023-02-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox_messages", "0016_remove_inboxes_vid_img_poster"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboxes",
            name="vid_duration",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
