# Generated by Django 4.1.4 on 2023-02-19 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inbox_messages", "0017_inboxes_vid_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inboxes",
            name="vid_duration",
        ),
    ]
