# Generated by Django 4.1.4 on 2023-03-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox_messages", "0019_chat_recipient_left_chat_chat_sender_left_chat"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inboxes",
            old_name="user",
            new_name="sender",
        ),
        migrations.AddField(
            model_name="inboxes",
            name="recipient_token",
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name="inboxes",
            name="sender_token",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
