# Generated by Django 4.1.4 on 2022-12-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="default_avatar.png",
                null=True,
                upload_to="profile_pictures",
                verbose_name="Picture",
            ),
        ),
    ]
