# Generated by Django 4.1.4 on 2022-12-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_alter_profile_facebook_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="facebook_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="instagram_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="whatsapp_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
