# Generated by Django 4.1.4 on 2022-12-27 03:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_alter_profile_facebook_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="instagram_url",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="whatsapp_url",
        ),
        migrations.AddField(
            model_name="profile",
            name="instagram_username",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="twitter_username",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="whatsapp_number",
            field=models.CharField(
                blank=True,
                max_length=17,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
    ]
