# Generated by Django 4.1.4 on 2022-12-31 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0013_remove_loginattempt_ip_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginattempt",
            name="username",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
