# Generated by Django 4.1.4 on 2023-01-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0015_alter_profile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
