# Generated by Django 4.1.4 on 2023-01-03 02:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0016_alter_profile_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="message_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
