# Generated by Django 4.1.4 on 2023-02-11 02:41

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0017_profile_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="avatar/default_avatar.png",
                null=True,
                upload_to=authentication.models.user_directory_path,
                verbose_name="Picture",
            ),
        ),
    ]
