# Generated by Django 4.1.4 on 2023-02-15 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("group_chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group_messages",
            old_name="group_chat",
            new_name="group_name",
        ),
    ]
